openapi: 3.0.0
info:
  title: Firebase ESP32 Data Ingestion API
  description: API for sending ESP32 data to Firebase Realtime Database.
  version: 1.0.0
servers:
  - url: https://{project_id}.firebaseio.com
    description: Firebase Realtime Database server
    variables:
      project_id:
        default: your_project_id
        description: The Firebase project ID

paths:
  /{race-car-telemetry}/{RawCANData}.json:
    post:
      summary: Send data to Firebase
      description: Sends data from the ESP32 to the specified collection in Firebase Realtime Database.
      parameters:
        - name: race-car-telemetry
          in: path
          required: true
          description: The Firebase project ID
          schema:
            type: string
        - name: RawCANData
          in: path
          required: true
          description: The name of the Firebase collection
          schema:
            type: string
      requestBody:
        description: JSON object containing the data sent from ESP32
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                timestamp: 0.053055
                can_id: 100
                length: 8
                data: 00 00 00 00 00 00 00 00
      responses:
        '200':
          description: Successful data ingestion
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
        '400':
          description: Bad request, invalid input
        '500':
          description: Server error
