name: CI Pipeline - Website and Arduino Compilation Check

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests targeting 'main'

jobs:
  # Job 1: Check if the website compiles
  website-compile:
    name: Check Website Compilation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up the Node.js environment
      - name: Set Up Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Navigate into the web app directory
      - name: Navigate to racecartelemetry_webapp
        working-directory: ./racecartelemetry_webapp
        run: |
          echo "Navigating to racecartelemetry_webapp"

      # Step 4: Install dependencies
      - name: Install Dependencies
        working-directory: ./racecartelemetry_webapp
        run: npm install

      # Step 5: Build the project (simulate production build)
      - name: Build Website
        working-directory: ./racecartelemetry_webapp
        run: npm run build

  # Job 2: Check if Arduino sketches compile
  arduino-compile:
    name: Compile Arduino Sketches
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Arduino CLI
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          arduino-cli config init

      # Step 3: Install Arduino cores
      - name: Install Arduino Cores
        run: |
          arduino-cli core update-index
          arduino-cli core install adafruit:samd # Install core for Adafruit Feather M4 CAN
          arduino-cli core install esp32:esp32   # Install core for ESP32 boards

      # Step 4: Compile all `.ino` files
      - name: Compile Arduino Sketches
        run: |
          for sketch in $(find . -name "*.ino"); do
            echo "Compiling $sketch for Adafruit Feather M4 CAN..."
            arduino-cli compile --fqbn adafruit:samd:adafruit_feather_m4_can $sketch
            echo "Compiling $sketch for ESP32..."
            arduino-cli compile --fqbn esp32:esp32:esp32 $sketch
          done
